deployment:
  name: "react-deployment"
  origin: "origin"   # The name of your remote (usually "origin")
  branch: "main"     # Or replace with your deployment branch, like "production"
  directory: "/home/bqhatuwa/public_html"  # The directory where your site should be deployed (check with your provider for the exact path)
  build:
    commands:
      - "yarn install"
      - "yarn build"  # Build the app
  artifacts:
    - "build"           # The build folder (replace with your folder if different)